apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp
  labels:
    app: gowebapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gowebapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
        - image: sabbir33/gowebapp
          imagePullPolicy: Always
          name: gowebapp
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gowebapp
  labels:
    app: gowebapp
spec:
  type: LoadBalancer
  selector:
    app: gowebapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
