apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp
  namespace: mynamespace
  image: adeelhussain13/gowebapp:latest
  labels:
    app: gowebapp
    namespace: mynamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gowebapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
        - image: adeelhussain13/gowebapp
          imagePullPolicy: Always
          name: gowebapp
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: gowebapp
  labels:
    app: gowebapp
spec:
  type: LoadBalancer
  selector:
    app: gowebapp
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
      protocol: TCP
